[package]
name = "evframework"
version = "0.1.0"
edition = "2021"

[dependencies]
textwrap = { version = "0.16", features = ["terminal_size"] }
crossterm = "0.28.1"

[lib]
name = "terminal"
path = "src/lib/terminal.rs"
